# How to complete this assignment
First, download [this Kaggle dataset](https://www.kaggle.com/hugomathien/soccer) and extract *sqlite* database. You may need to register at https://www.kaggle.com/ beforehand. Then complete 15 graded tasks below, the score is given in brackets. Finally submit the resulting `.ipynb` file to rs-app Auto-test.

- Do not delete or rename the variables given before the inscription `#your code here`, they are needed for the correct verification.
- Do not change the code in the last Notebook cell, it is required for the server check.
- Your Notebook must run completely without errors to be graded! Please check everything before submission by going *Cell -> Run All*

## Some important notes
- If you need to **calculate the number of "something"** that means we expect you to assign an Integer to the given variable
- If you need to **make a list of "something"** we expect you to assign a Python list with appropriate values to the given variable
- If you need to find a **specifi—Å player, day of the week, team, etc.** we expect you to assign a String with the full name of the entity to the given variable (`player_name`, day of week full name, `team_name`, etc.)

In [66]:
import sqlite3
import pandas as pd
import os
import numpy as np

pd.set_option('display.max_column', None)

In [67]:
# Leave that code unchanged, it is required for the server check!
db = sqlite3.connect(os.environ.get("DB_PATH") or 'database.sqlite')

In [68]:
# You may load the data from SQL table directly to the Pandas dataframe as
player_data = pd.read_sql("SELECT * FROM Player;", db)
league_data = pd.read_sql("SELECT * FROM League;", db)
match_data = pd.read_sql("SELECT * FROM Match;", db)
player_att_data = pd.read_sql("SELECT * FROM Player_Attributes;", db)
team_data = pd.read_sql("SELECT * FROM Team;", db)

In [69]:
player_data.head()

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154

**Task 1 (0.25 point).** Calculate the number of players with a height between 180 and 190 inclusive

In [70]:
players_180_190 = player_data[(player_data.height >= 180) & (player_data.height <= 190)].shape[0]

**Task 2 (0.25 point).** Calculate the number of players born in 1980. <br>
**Hint:** you may want to cast your 'birthday' column to DateTime type by [pandas.to_datetime](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html)

In [71]:
players_1980 = player_data[pd.to_datetime(player_data.birthday).dt.strftime('%Y') == '1980'].shape[0]

**Task 3 (0.25 point).** Make a list of the top 10 players with the highest weight sorted in descending order. If there are several players with the same weight put them in the lexicographic order by name.

In [72]:
highest_players = player_data.sort_values(by=['weight', 'player_name'], ascending=(False, True)).head(10)['player_name'].values.tolist()

**Task 4 (0.5 point).** Make a list of tuples containing years along with the number of players born in that year from 1980 up to 1990. <br>
**Structure example**: [(1980, 123), (1981, 140) ..., (1990, 83)] -> There were born 123 players in 1980, there were born 140 players in 1981 and etc.

In [73]:
num_by_year = player_data[(pd.to_datetime(player_data.birthday).astype('datetime64[Y]') >= '1980') & \
            (pd.to_datetime(player_data.birthday).astype('datetime64[Y]') <= '1990')] \
            .groupby(pd.to_datetime(player_data.birthday).astype('datetime64[Y]')).size()
years_born_players = list(zip(num_by_year.index.year, num_by_year))

**Task 5 (0.5 point).** Calculate the mean and the standard deviation of the players' **height** with the name **Adriano**. <br>
**Note:** Name is represented by the first part of `player_name`.

In [74]:
adrianos_heights = player_data[player_data.player_name.str.startswith('Adriano')]['height']
adriano_mean, adriano_std = adrianos_heights.mean(), adrianos_heights.std()

**Task 6 (0.75 point).** How many players were born on each day of the week? Find the day of the week with the minimum number of players born.

In [75]:
dow_with_min_players_born = player_data.groupby(pd.to_datetime(player_data.birthday).dt.strftime('%A')) \
                                        .size().sort_values().index[0]

**Task 7 (0.75 point).** Find a league with the most matches in total. If there are several leagues with the same amount of matches, take the first in the lexical order.

In [76]:
match_data.sample(5)

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
20333,20334,19694,19694,2010/2011,37,2011-05-11 00:00:00,1005036,9927,8597,1,1,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,37780.0,160568.0,43246.0,156019.0,35502.0,40137.0,25975.0,181227.0,37294.0,23117.0,43251.0,32713.0,32694.0,4939.0,102777.0,32696.0,150260.0,150707.0,13917.0,32907.0,179801.0,41941.0,None,None,None,None,None,None,None,None,2.25,3.40,3.10,2.20,3.20,2.9,2.10,3.10,3.2,2.38,3.40,2.88,NaN,NaN,NaN,2.15,3.1,3.00,2.25,3.30,3.00,2.38,3.50,3.00,2.20,3.2,3.00,2.20,3.3,3.10
4442,4443,1729,1729,2015/2016,14,2015-11-29 00:00:00,1988844,8650,10003,1,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,37868.0,157838.0,22764.0,114268.0,314605.0,38807.0,307021.0,280653.0,242709.0,37234.0,148315.0,30973.0,111800.0,165704.0,24948.0,102356.0,23882.0,144996.0,38831.0,157729.0,95955.0,150026.0,<goal><value><comment>p</comment><stats><penal...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>66</comment><stats...,1.44,4.75,8.00,1.45,4.40,7.5,1.50,4.00,6.1,1.50,4.33,7.00,1.48,4.55,7.95,1.50,4.0,7.00,NaN,NaN,NaN,1.45,4.75,8.00,NaN,NaN,NaN,NaN,NaN,NaN
2425,2426,1729,1729,2009/2010,38,2010-05-09 00:00:00,659376,10260,10194,4,0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,30726.0,30615.0,30620.0,30865.0,32569.0,40945.0,24148.0,30373.0,24154.0,27430.0,30829.0,46518.0,23369.0,40695.0,38899.0,35467.0,25668.0,24411.0,23253.0,24773.0,23314.0,38755.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>52</comment><event...,1.13,8.00,23.00,1.12,7.75,17.0,1.10,7.30,15.0,1.11,9.00,19.00,NaN,NaN,NaN,1.11,8.5,21.00,1.11,9.00,21.00,1.12,7.00,23.00,1.12,8.0,19.00,1.11,7.5,23.00
6379,6380,4769,4769,2012/2013,18,2012-12-16 00:00:00,1216982,8481,9827,1,1,1.0,1.0,3.0,5.0,7.0,9.0,3.0,5.0,7.0,4.0,6.0,1.0,1.0,3.0,5.0,7.0,9.0,3.0,5.0,7.0,4.0,6.0,1.0,3.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,26290.0,46232.0,145058.0,26245.0,26244.0,240236.0,17875.0,41098.0,240367.0,74838.0,157859.0,26168.0,122047.0,179393.0,26119.0,26118.0,41092.0,292772.0,26238.0,94010.0,31292.0,41238.0,<goal><value><comment>n</comment><stats><goals...,<shoton />,<shotoff />,<foulcommit />,<card><value><comment>y</comment><stats><ycard...,<cross />,<corner />,<possession />,3.30,3.20,2.25,3.50,3.00,2.2,3.45,3.15,2.1,3.60,3.20,2.10,3.48,3.26,2.34,3.50,3.1,2.20,3.30,3.13,2.25,3.50,3.20,2.30,3.50,3.0,2.20,3.40,3.1,2.25
18582,18583,17642,17642,2011/2012,7,2011-10-02 00:00:00,1042883,10214,2033,1,0,1.0,2.0,4.0,6.0,8.0,5.0,3.0,5.0,7.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,5.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,277693.0,19524.0,101201.0,164319.0,45280.0,31310.0,185143.0,74232.0,115719.0,114651.0,181362.0,124127.0,164001.0,43289.0,191788.0,185949.0,11726.0,171968.0,42773.0,NaN,154268.0,96615.0,None,None,None,None,None,None,None,None,2.10,3.10,3.80,2.00,3.10,3.9,2.00,3.00,3.6,2.10,3.00,3.20,NaN,NaN,NaN,2.00,3.1,3.75,2.00,3.10,3.75,2.10,3.20,3.75,2.00,3.1,3.75,2.05,3.1,3.50

In [77]:
num_of_mathes_for_each_league = match_data.groupby(match_data.league_id).size().sort_values(ascending=False) \
                                            .rename('matches')
league_most_matches = pd.merge(num_of_mathes_for_each_league, league_data[['id', 'name']], right_on='id', left_index=True) \
                        .sort_values(by=['matches', 'name'], ascending=(False, True)).iloc[0]['name']

**Task 8 (1.25 point).** Find a player who participated in the largest number of matches during the whole match history. Assign a `player_name` to the given variable

In [78]:
players_id, counts = np.unique(match_data.loc[:,'home_player_1' : 'away_player_11'].dropna().values, return_counts=True)
max_matches_player = player_data[player_data.player_api_id == players_id[counts.argmax()]].iloc[0]['player_name']

**Task 9 (1.5 point).** List top-5 tuples of most correlated **player's characteristics** in the descending order of the absolute [Pearson's coefficient](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient) value.

**Note 1:** Players characteristics are all the columns in `Player_Attributes` table except `[id, player_fifa_api_id, player_api_id, date, preferred_foot, attacking_work_rate, defensive_work_rate]`). <br>
**Note 2:** Exclude duplicated pairs from the list. E.g. ('gk_handling', 'gk_reflexes') and ('gk_reflexes', 'gk_handling') are duplicates, leave just one of them in the resulting list.

**Hint:** You may use [dataframe.corr()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html) for calculating pairwise Pearson correlation.

In [79]:
x = player_att_data.loc[:, ~player_att_data.columns.isin(['id', 'player_fifa_api_id', 'player_api_id', 'date', 'preferred_foot', \
                                                          'attacking_work_rate', 'defensive_work_rate'])].corr()
top_correlated_features = x.where(np.triu(np.ones(x.shape), k=1).astype(bool)).stack() \
                            .sort_values(ascending=False)[:5].index.tolist()

**Task 10 (2 points).** Find top-5 most similar players to **Neymar** whose names are given. The similarity is measured as [Euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) between vectors of players' characteristics (described in the task above). Put their names in a vector in ascending order by Euclidean distance and sorted by `player_name` if the distance is the same<br>
**Note 1:** There are many records for some players in the `Player_Attributes` table. You need to take the freshest data (characteristics with the most recent `date`). <br>
**Note 2:** Use pure values of the characteristics even if you are aware of such preprocessing technics as normalization. <br>
**Note 3:** Please avoid using any built-in methods for calculating the Euclidean distance between vectors, think about implementing your own.

In [80]:
# player_att_data.loc[:, ~player_att_data.columns.isin(['id', 'player_fifa_api_id', 'player_api_id', 'date', 'preferred_foot', \
#                                                           'attacking_work_rate', 'defensive_work_rate'])]
neymar_api_id = player_data[player_data.player_name == 'Neymar'].iloc[0]['player_api_id']
player_att_data_10 = player_att_data[:].dropna()
player_att_data_10['date'] = pd.to_datetime(player_att_data_10.date)
neymar_attr = player_att_data_10[player_att_data_10.player_api_id == neymar_api_id].sort_values(by='date', ascending=False).head(1) \
                                                                .loc[:, ~player_att_data_10.columns.isin(['id', 'player_fifa_api_id', 'player_api_id', 'date', 'preferred_foot', \
                                                          'attacking_work_rate', 'defensive_work_rate'])]
last_measures_dates = player_att_data_10.groupby('player_api_id')['date'].max()
latest_measures = pd.merge(last_measures_dates, player_att_data_10, on=['player_api_id', 'date']).loc[:, ~player_att_data.columns.isin(['player_fifa_api_id', 'date', 'preferred_foot', \
                                                          'attacking_work_rate', 'defensive_work_rate'])]
latest_measures['euclidian_distance'] = latest_measures.loc[:, 'overall_rating':'gk_reflexes'].sub(neymar_attr.squeeze()).pow(2).sum(axis=1)
closest_players_ids = latest_measures.sort_values(by='euclidian_distance').head(6).iloc[1:]['player_api_id']
neymar_similarities = pd.merge(closest_players_ids, player_data, on='player_api_id').iloc[:]['player_name'].tolist()

**Task 11 (1 point).** Calculate the number of home matches played by the **Borussia Dortmund** team in **Germany 1. Bundesliga** in season **2008/2009**

In [81]:
bd_team_id = team_data[team_data.team_long_name == 'Borussia Dortmund'].iloc[0]['team_api_id']
bundesleague_id = league_data[league_data.name == 'Germany 1. Bundesliga'].iloc[0]['id']
borussia_bundesliga_2008_2009_matches = match_data[(match_data.season == '2008/2009') & \
                                                   (match_data.home_team_api_id == bd_team_id) & \
                                                   (match_data.league_id == bundesleague_id)].shape[0]

In [82]:
league_data.sample(5)

       id  country_id                      name
10  24558       24558  Switzerland Super League
7   17642       17642  Portugal Liga ZON Sagres
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
4   10257       10257             Italy Serie A

In [83]:
team_data.sample(7)

        id  team_api_id  team_fifa_api_id       team_long_name team_short_name
197  31925         8245          111083.0        Korona Kielce             KKI
205  35283         9773             236.0             FC Porto             POR
70    9548         9847              73.0  Paris Saint-Germain             PSG
258  43042         8634             241.0         FC Barcelona             BAR
289  49120        10179          110770.0              FC Sion             SIO
162  26553         8464            1910.0               N.E.C.             NEC
195  31457         8028          111086.0        Piast Gliwice             PIG

In [84]:
match_data.sample(7)

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
25089,25090,24558,24558,2010/2011,8,2010-09-12 00:00:00,845061,7955,10190,0,1,1.0,2.0,4.0,6.0,8.0,1.0,3.0,5.0,7.0,9.0,5.0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,7.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,66902.0,95217.0,25863.0,38626.0,26065.0,101503.0,173011.0,92095.0,25860.0,139634.0,197515.0,42113.0,25782.0,114789.0,26558.0,173609.0,39843.0,114790.0,95228.0,95216.0,128235.0,114794.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17020,17021,15722,15722,2013/2014,20,2013-12-06 00:00:00,1468016,8028,8245,1,1,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,4.0,6.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,6.0,8.0,8.0,11.0,206805.0,208315.0,11061.0,43135.0,78537.0,412981.0,208388.0,139779.0,118530.0,68877.0,289178.0,32633.0,178435.0,94419.0,12374.0,429655.0,36641.0,429657.0,69256.0,69258.0,147616.0,13383.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16167,16168,15722,15722,2009/2010,5,2009-08-28 00:00:00,673738,8028,8242,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13494.0,NaN,NaN,150670.0,NaN,NaN,NaN,NaN,69628.0,105535.0,4999.0,NaN,NaN,NaN,NaN,NaN,NaN,13405.0,NaN,116756.0,68839.0,NaN,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,58,1,1,2008/2009,15,2008-12-06 00:00:00,492692,9986,8203,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.67,3.4,5.0,1.60,3.50,4.90,1.65,3.3,4.4,1.62,3.50,4.50,NaN,NaN,NaN,1.65,3.4,4.5,1.70,3.5,5.25,1.65,3.5,4.5,1.67,3.4,4.6,1.67,3.4,4.75
10690,10691,10257,10257,2009/2010,14,2009-11-29 00:00:00,704579,8533,8540,1,0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,5.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,5.0,4.0,6.0,1.0,3.0,3.0,3.0,3.0,5.0,5.0,5.0,8.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,5.0,5.0,5.0,8.0,10.0,10.0,39477.0,39273.0,113762.0,39721.0,24443.0,27731.0,42651.0,39286.0,42003.0,39745.0,24448.0,27659.0,39422.0,35112.0,39419.0,24622.0,39367.0,31288.0,34540.0,33337.0,49677.0,32747.0,<goal><value><comment>n</comment><stats><goals...,<shoton />,<shotoff />,<foulcommit />,<card><value><comment>y</comment><stats><ycard...,<cross />,<corner />,<possession />,2.30,3.2,3.2,2.40,3.05,2.95,2.30,3.2,3.0,2.25,3.00,2.88,NaN,NaN,NaN,2.30,3.1,3.0,2.38,3.0,3.25,2.25,3.1,3.2,2.35,3.1,3.0,2.30,3.2,3.00
4164,4165,1729,1729,2014/2015,23,2015-02-01 00:00:00,1724208,8466,10003,0,1,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,95336.0,157838.0,26552.0,72665.0,46010.0,502420.0,23792.0,94267.0,279490.0,26675.0,41280.0,30973.0,111800.0,155050.0,24948.0,102356.0,NaN,212702.0,23305.0,127130.0,28108.0,26344.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>66</comment><event...,1.60,4.0,6.5,1.62,3.90,6.00,1.65,3.6,5.1,1.61,3.75,6.00,1.62,3.99,6.62,1.62,3.6,6.0,NaN,NaN,NaN,1.60,3.9,7.0,NaN,NaN,NaN,NaN,NaN,NaN
16521,16522,15722,15722,2011/2012,19,2012-02-25 00:00:00,1031166,2186,1957,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93450.0,13504.0,NaN,NaN,NaN,NaN,30880.0,NaN,NaN,NaN,NaN,114822.0,50657.0,279865.0,NaN,NaN,116872.0,39798.0,34225.0,249550.0,206829.0,NaN,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Task 12 (1 point).** Find a team having the most matches (both home and away!) in the **Germany 1. Bundesliga** in **2008/2009** season. Return number of matches.

In [85]:
away_matches = match_data[(match_data.season == '2008/2009') & (match_data.league_id == bundesleague_id)] \
                        .groupby('away_team_api_id').size()
home_matches = match_data[(match_data.season == '2008/2009') & (match_data.league_id == bundesleague_id)] \
                        .groupby('home_team_api_id').size()
team_most_matches_bundesliga_2008_2009 = away_matches.add(home_matches).sort_values(ascending=False).iloc[0]

**Task 13 (1 point).** Count total number of **Arsenal** matches (both home and away!) in the **2015/2016** season which they have won. <br><br>
**Note:** Winning a game means scoring **more** goals than an opponent.

In [86]:
arsenal_id = team_data[team_data.team_long_name == 'Arsenal'].iloc[0]['team_api_id']
num_home_won_mathes = match_data[(match_data.season == '2015/2016') & (match_data.home_team_api_id == arsenal_id) & \
                                 (match_data.home_team_goal > match_data.away_team_goal)].shape[0]
num_away_won_mathes = match_data[(match_data.season == '2015/2016') & (match_data.away_team_api_id == arsenal_id) & \
                                 (match_data.away_team_goal > match_data.home_team_goal)].shape[0]
arsenal_won_matches_2015_2016 = num_home_won_mathes + num_away_won_mathes

**Task 14 (2 points).** Find a team with the highest win rate in the **2015/2016** season. Win rate means won matches / all matches. If there are several teams with the highest win rate return the first by name in lexical order

In [87]:
won_at_home = match_data[(match_data.season == '2015/2016') & (match_data.home_team_goal > match_data.away_team_goal)] \
                        .groupby('home_team_api_id').size()
won_away = match_data[(match_data.season == '2015/2016') & (match_data.home_team_goal < match_data.away_team_goal)] \
                        .groupby('away_team_api_id').size()
all_at_home = match_data[match_data.season == '2015/2016'].groupby('home_team_api_id').size()
all_away = match_data[match_data.season == '2015/2016'].groupby('away_team_api_id').size()
id_team_highest_winrate = won_at_home.add(won_away).divide(all_at_home.add(all_away)).sort_values(ascending=False).index[0]
team_highest_winrate_2015_2016 = team_data[team_data.team_api_id == id_team_highest_winrate].iloc[0]['team_long_name']

**Task 15 (2 points).** Determine the team with the maximum days' gap between matches in **England Premier League 2010/2011 season**. Return number of days in that gap. <br>
**Note**: a *gap* means the number of days between two consecutive matches of the same team.

In [88]:
eng_league_id = league_data[league_data.name == 'England Premier League'].iloc[0]['id']
matches_eng_league = match_data[(match_data.season == '2010/2011') & (match_data.league_id == eng_league_id)]
home_matches_eng = matches_eng_league[['date','home_team_api_id']].rename(columns={'home_team_api_id': 'team_api_id'}) 
away_matches_eng = matches_eng_league[['date','away_team_api_id']].rename(columns={'away_team_api_id': 'team_api_id'})
team_date = pd.concat([home_matches_eng, away_matches_eng])
team_date['date'] = pd.to_datetime(team_date['date'])
gaps = team_date.sort_values(by=['team_api_id', 'date'], ascending=(True, True)).diff()
highest_gap_england_2010_2011 = gaps[gaps.team_api_id == 0].sort_values(by='date', ascending=False).iloc[0]['date'].days

### Warning! Do not change anything in the area below

In [89]:
with open('student_answers.txt', 'w') as file:
    file.write(f"{players_180_190}\n")
    file.write(f"{players_1980}\n")
    file.write(f"{highest_players}\n")
    file.write(f"{years_born_players}\n")
    file.write(f"{round(adriano_mean, 3)} {round(adriano_std, 3)}\n")
    file.write(f"{dow_with_min_players_born}\n")
    file.write(f"{league_most_matches}\n")
    file.write(f"{max_matches_player}\n")
    file.write(f"{';'.join(['%s,%s' % tup for tup in top_correlated_features])};\n")
    file.write(f"{neymar_similarities}\n")
    file.write(f"{borussia_bundesliga_2008_2009_matches}\n")
    file.write(f"{team_most_matches_bundesliga_2008_2009}\n")
    file.write(f"{arsenal_won_matches_2015_2016}\n")
    file.write(f"{team_highest_winrate_2015_2016}\n")
    file.write(f"{highest_gap_england_2010_2011}\n")